configuration:
questions:
  question: Which response class?
  answers:
    - There is a problem with the response:
      question: Is the user being throttled?
      answers:
        - yes:
          question: Are you Twitter or Facebook size?
          answers:
            - yes:
              result: 420 Enhance your calm
            - no:
              result: 429 Too many requests
        - no:
          question: Does the user need to authenticate?
          answers:
            - yes:
              question: Are you using HTTP auth?
    - There is a problem server-side:
      question:
      answers:
    - I am implementing a web server:
      question:
      answers:
